function export_fields = tm_get_export_fields(task)
%% tm_get_cryocare_fields
% Return parameter fields for a given tomoman_cryoCARE task. 
%
% WW 06-2023

%% Get fields

switch task
    case 'export_relion4'
        export_fields = {'output_dir','str';...
                           % 'sg_wedgelist','str';...
                           'sg_motl','str';...
                           'process_stack','str';...
                           'export_list','str';...
                           'no_tomo_export','boo';...
                           };
        
    case 'export_warp'
        export_fields = {'output_dir','str';...
                           'sg_motl','str';...
                           'process_stack','str';...
                           'export_list','str';...
                           'no_tomo_export','boo';...
                           };

        
    case 'export_stopgap'
        error('In construction!!!')
end




