function tomoman_imod_batch3dfind_generate_imod_scripts(t,p,tiltcom)
%% will_novactf_generate_parallel_scripts
% A function for generating a set of scripts for parallel processing of
% tilt-stacks for NovaCTF. 
%
% WW 01-2018

%% Initialize

% % Generate job array
% job_array = will_job_array(n_stacks,p.n_cores);
% n_jobs = size(job_array,1);
% if n_jobs < p.n_cores
%     disp(['ACHTUNG!!! For tomogram ',num2str(t.tomo_num),' there are fewer stacks than number of allotted cores!!!']);
% end

% Stackname
switch p.stack
    case 'r'
        stack_name = t.stack_name;
    case 'w'
        [~,name,~] = fileparts(t.stack_name);
        stack_name = [name,'-whitened.st'];
    case 'df'
        stack_name = t.dose_filtered_stack_name;
    case 'dfw'
        [~,name,~] = fileparts(t.dose_filtered_stack_name);
        stack_name = [name,'-whitened.st'];
end
        

% Parse tlt filename
[~,name,~] = fileparts(t.dose_filtered_stack_name);
tltname = [name,'.tlt'];

tilts = dlmread([t.stack_dir,tltname]);

% Parse transform file anme
xform_file = [name,'.xf'];





%% Write parallel scripts

% Base name of parallel scripts
pscript_name = [t.stack_dir,'imod_batch3dfind/stack_process.sh'];

    
% Open script
pscript = fopen(pscript_name,'w');

% Write initial lines
fprintf(pscript,['#!/usr/bin/env bash \n\n','set -e \n','set -o nounset \n\n']);


% Write comment line
fprintf(pscript,['echo "##### Processing stack ',stack_name,' #####"','\n\n\n']);




% Generate aligned stack
fprintf(pscript,['# Generate aligned stack','\n']);
fprintf(pscript,['newstack -in ',t.stack_dir,stack_name,' ',...
                 '-ou ',t.stack_dir,'imod_batch3dfind/aligned_stack.ali ',...
                 '-xform ',t.stack_dir,xform_file,' ',...
                 '-BinByFactor ',num2str(p.beadfind_binning),'\n\n']);

% Reconstruct with tilt
fprintf(pscript,['# Reconstruct tomogram with tilt','\n']);
fprintf(pscript,['tilt ',...
                '-InputProjections ', t.stack_dir,'imod_batch3dfind/aligned_stack.ali ',...
                '-OutputFile ', t.stack_dir,'imod_batch3dfind/3dfind.rec ',...
                '-IMAGEBINNED ',num2str(p.beadfind_binning),' ',...
                '-TILTFILE ', t.stack_dir,tltname,' ',...
                '-THICKNESS ',num2str(tiltcom.THICKNESS),' ',...
                '-RADIAL ',num2str(tiltcom.RADIAL(1)),',', num2str(tiltcom.RADIAL(2)),' ',...
                '-FalloffIsTrueSigma 1 ',...
                '-XAXISTILT ',num2str(tiltcom.XAXISTILT),' ',...
                '-PERPENDICULAR  ',...
                '-MODE 2 ',...
                '-FULLIMAGE ',num2str(tiltcom.FULLIMAGE(1)),',', num2str(tiltcom.FULLIMAGE(2)),' ',...
                '-SUBSETSTART ',num2str(tiltcom.SUBSETSTART(1)),',', num2str(tiltcom.SUBSETSTART(2)),' ',...
                '-AdjustOrigin  ',...
                '-OFFSET ',num2str(tiltcom.OFFSET),' ',...
                '-UseGPU 0 ',...
                '-ActionIfGPUFails 1,1 ',...
                '-SHIFT ',num2str(tiltcom.SHIFT(1)),',', num2str(tiltcom.SHIFT(2)),' \n\n\n']);

% Find gold beads
if ~isempty(p.goldradius)
    fprintf(pscript,['# Find gold beads','\n']);
    fprintf(pscript,['findbeads3d -InputFile ',t.stack_dir,'/imod_batch3dfind/3dfind.rec ',...
    '-OutputFile ',t.stack_dir,'/imod_batch3dfind/3dfind.mod ',...
    '-BeadSize ',num2str(p.goldradius),' ',...
    '-MinRelativeStrength 0.05 ',...
    '-StorageThreshold 0.0 ',...
    '-MinSpacing 0.9 ',...
    '-BinningOfVolume ',num2str(p.beadfind_binning), '\n\n']);
end



             
% Reproject bead model with tilt
fprintf(pscript,['# Reconstruct tomogram with tilt','\n']);
fprintf(pscript,['tilt ',...
                '-InputProjections ', t.stack_dir,'/imod_batch3dfind/aligned_stack.ali ',...
                '-OutputFile ', t.stack_dir,name,'_erase.fid ',...
                '-ProjectModel ', t.stack_dir,'/imod_batch3dfind/3dfind.mod ',...
                '-IMAGEBINNED ',num2str(p.beadfind_binning),' ',...
                '-TILTFILE ', t.stack_dir,tltname,' ',...
                '-THICKNESS ',num2str(tiltcom.THICKNESS),' ',...
                '-RADIAL ',num2str(tiltcom.RADIAL(1)),',', num2str(tiltcom.RADIAL(2)),' ',...
                '-FalloffIsTrueSigma 1 ',...
                '-XAXISTILT ',num2str(tiltcom.XAXISTILT),' ',...
                '-PERPENDICULAR  ',...
                '-MODE 2 ',...
                '-FULLIMAGE ',num2str(tiltcom.FULLIMAGE(1)),',', num2str(tiltcom.FULLIMAGE(2)),' ',...
                '-SUBSETSTART ',num2str(tiltcom.SUBSETSTART(1)),',', num2str(tiltcom.SUBSETSTART(2)),' ',...
                '-AdjustOrigin  ',...
                '-OFFSET ',num2str(tiltcom.OFFSET),' ',...
                '-UseGPU 0 ',...
                '-ActionIfGPUFails 1,1 ',...
                '-SHIFT ',num2str(tiltcom.SHIFT(1)),',', num2str(tiltcom.SHIFT(2)),' \n\n\n']);


fclose(pscript);    % Close script
% Make executable
system(['chmod +x ',pscript_name]);

        


