function tomoman_fcropcluster_generate_tomogram_runscript(t,p)
%% will_novactf_generate_tomogram_runscript
% A function to generate a 'runscript' for running novaCTF on a tilt-stack.
% When run, the runscript first runs parallel processing of tilt-stacks via
% MPI; when the MPI job is completed, it finishes the tomogram by running
% novaCTF. The tomogram is then binned via Fourier cropping and the 
% intermediate files are deleted. 
%
% WW 01-2018

%% Generate run script

% Open run script
rscript = fopen([t.stack_dir,'/binning/run_binning.sh'],'w');


% Write initial lines for submission on either local or hpcl700x (p.512g)
% 
switch p.queue
    case 'p.512g'
        error('Oops!! 404');
%         fprintf(rscript,['#! /usr/bin/env bash\n\n',...
%             '#$ -pe openmpi 40\n',...            % Number of cores
%             '#$ -l h_vmem=128G\n',...            % Memory limit
%             '#$ -l h_rt=604800\n',...              % Wall time
%             '#$ -q ',p.queue,'\n',...                       %  queue
%             '#$ -e ',t.stack_dir,'/novactf/error_novactf\n',...       % Error file
%             '#$ -o ',t.stack_dir,'/novactf/log_novactf\n',...         % Log file
%             '#$ -S /bin/bash\n',...                      % Submission environment
%             'source ~/.bashrc\n\n',]);                      % Get proper envionment; i.e. modules

    case 'p.192g'
        error('Oops!! 404');
%         fprintf(rscript,['#! /usr/bin/env bash\n\n',...
%             '#$ -pe openmpi 16\n',...            % Number of cores
%             '#$ -l h_vmem=128G\n',...            % Memory limit
%             '#$ -l h_rt=604800\n',...              % Wall time
%             '#$ -q ',p.queue,'\n',...                       %  queue
%             '#$ -e ',t.stack_dir,'/novactf/error_novactf\n',...       % Error file
%             '#$ -o ',t.stack_dir,'/novactf/log_novactf\n',...         % Log file
%             '#$ -S /bin/bash\n',...                      % Submission environment
%             'source ~/.bashrc\n\n',]);                      % Get proper envionment; i.e. modules        
    case 'local'
        fprintf(rscript,['#!/usr/bin/env bash \n\n','echo $HOSTNAME\n','set -e \n','set -o nounset \n\n']);
            
    case 'p.hpcl67'
        fprintf(rscript,['#!/bin/bash -l\n',...
            '# Standard output and error:\n',...
            '#SBATCH -e ' ,t.stack_dir,'/binning/error_binning\n',...
            '#SBATCH -o ' ,t.stack_dir,'/binning/log_binning\n',...
            '# Initial working directory:\n',...
            '#SBATCH -D ./\n',...
            '# Job Name:\n',...
            '#SBATCH -J Fourier3D\n',...
            '# Queue (Partition):\n',...
            '#SBATCH --partition=p.hpcl67 \n',...
            '# Number of nodes and MPI tasks per node:\n',...
            '#SBATCH --nodes=1\n',...
            '#SBATCH --ntasks=40\n',...
            '#SBATCH --ntasks-per-node=40\n',...
            '#SBATCH --cpus-per-task=1\n',...            %'#SBATCH --gres=gpu:2\n',...
            '#\n',...
            '#SBATCH --mail-type=none\n',...
            '#SBATCH --mem 510000\n',...
            '#\n',...
            '# Wall clock limit:\n',...
            '#SBATCH --time=168:00:00\n',...
            'echo "setting up environment"\n',...
            'module purge\n',...
            'module load intel/18.0.5\n',...
            'module load impi/2018.4\n',...
            '#load module for your application\n',...
            'module load FOURIER3D/06-10-20\n',...
            'module load IMOD/4.10.49\n',...
            'export IMOD_PROCESSORS=40\n']);                      % Get proper envionment; i.e. modules

    case 'p.hpcl8'
        fprintf(rscript,['#!/bin/bash -l\n',...
            '# Standard output and error:\n',...
            '#SBATCH -e ' ,t.stack_dir,'/binning/error_binning\n',...
            '#SBATCH -o ' ,t.stack_dir,'/binning/log_binning\n',...
            '# Initial working directory:\n',...
            '#SBATCH -D ./\n',...
            '# Job Name:\n',...
            '#SBATCH -J Fourier3d\n',...
            '# Queue (Partition):\n',...
            '#SBATCH --partition=p.hpcl8 \n',...
            '# Number of nodes and MPI tasks per node:\n',...
            '#SBATCH --nodes=1\n',...
            '#SBATCH --ntasks=1\n',...
            '#SBATCH --ntasks-per-node=1\n',...
            '#SBATCH --cpus-per-task=24\n',...
            '#SBATCH --gres=gpu:2\n',...
            '#\n',...
            '#SBATCH --mail-type=none\n',...
            '#SBATCH --mem 378880\n',...
            '#\n',...
            '# Wall clock limit:\n',...
            '#SBATCH --time=168:00:00\n',...
            'echo "setting up environment"\n',...
            'module purge\n',...
            'module load intel/18.0.5\n',...
            'module load impi/2018.4\n',...
            '#load module for your application\n',...
            'module load IMOD/4.10.43\n',...
            'module load FOURIER3D\n',...
            'export IMOD_PROCESSORS=24']);                      % Get proper envionment; i.e. modules
        
        
    otherwise
            error('only "local" or "p.hpcl67" or "hpcl8" supported queques for p.queue!!!!')
        
    
end



% Bin tomogram
in_name = [p.main_dir,'/',num2str(t.tomo_num),'.rec'];  % Input tomogram name
for i = 1:numel(p.tomo_bin)
    
    % Ouptut tomogram name
    out_name = [p.bin_dir{i},'/',num2str(t.tomo_num),'.rec'];
    
    fprintf(rscript,['# Fourier crop tomogram by a factor of ',num2str(prod(p.tomo_bin(1:i))),'\n']);
    fprintf(rscript,[p.fcrop_vol,' ',...
                     '-InputFile ',in_name,' ',...
                     '-OutputFile ',out_name,' ',...
                     '-BinFactor ',num2str(p.tomo_bin(i)),' ',...
                     '-MemoryLimit ',num2str(p.fcrop_vol_memlimit),' ',...
                     '> ',t.stack_dir,'binning/binning_log.txt 2>&1','\n\n']);
    
    % Set for serial binning on next pass
    in_name = out_name;
end

% Close file and make executable
fclose(rscript);
system(['chmod +x ',t.stack_dir,'/binning/run_binning.sh']);

                 


