function novactf_fields = tm_get_novactf_fields()
%% tm_get_novactf_fields
% Return input fields for novaCTF tomogram reconstruction. 
%
% WW 07-2022

%% Fields

novactf_fields = {'n_cores','num';...
                  'famp','num';...
                  'cs','num';...
                  'ali_dim','num';...
                  'erase_radius','num';...
                  'taper_pixels','num';...
                  'ali_stack_bin','num';...
                  'process_stack','str';...
                  'correction_type','str';...
                  'defocus_step','num';...
                  'radial','num';...
                  'tomo_bin','num';...
                  'output_dir_prefix','str';...
                  'recons_list','str';...
                  'force_novactf','boo';...
                  'f3d_memlimit','num';...
                  'cen_mass_name', 'str';...
                  };
             
end
                 






