function tasks = tm_get_nonparallel_tasks()
%% tm_get_nonparallel_tasks
% Return a cell array with all non-parallel tomoman tasks.
%
% WW 07-2022


%% Task list
tasks = {'import';...
         'clean_stacks';...
         'imod_reconstruct';...
         'must_reconstruct';...
         'cryocare_oe_recons';...
         'cryocare_train';...
         'cryocare_predict';...
         'isonet_prepare';...
         'isonet_train';...
         'isonet_predict';...
         'membrain_segment';...
         'isonet2_prepare';...
         'isonet2_denoise';...
         'isonet2_make_mask';...
         'isonet2_make_particle_mask';...
         'isonet2_refine';...
         };
     
     
end