function tctf = tomoman_tiltctf_parser(tctf)
%% tomoman_parse_tiltctf_param
% Parse and check the input parameters for tiltctf.
%
% WW 07-2018

%% Parse!!!1!

% Parameter array
param = {'imod_stack', 'str';...
         'force_run', 'boo';...
         'ps_size', 'num';...
         'def_tol', 'num';...
         'fscaling', 'num';...
         'xtiltoption','num';...
         'calc_ps','bool';...
         'invert_tiltangle_sign','bool';...
         'ifgpu','bool';...
         'gpudevice', 'num';...
         'write_unstretched', 'boo';...
         'write_negative', 'boo';...
         'visualdebug' , 'boo';...
         };
n_param = size(param,1);


% Check types
for i = 1:n_param
    tctf.(param{i,1}) = tomoman_check_param_type(tctf.(param{i,1}),param{i,1},param{i,2});
end
    
% Check imod_stack
if ~any(strcmp(tctf.imod_stack,{'unfiltered','dose_filt'}))
    error('ACTHUNG!!! Unsuppored imod_stack... Only "unfiltered" and "dose_filt" supported!!!');
end



