function tasks = tm_get_tasks()
%% tm_get_tasks
% Return a cell array with all tomoman tasks.
%
% WW 06-2022


%% Task list
tasks = {'pipeline';...     % Always leave pipeline as first
         'import';...
         'relion_motioncorr';...
         'motioncor2';...
         'motioncor3';...
         'clean_stacks';...
         'dosefilter';...
         'aretomo';...
         'ctffind4';...
         'tiltctf';...
         'imod_preprocess';...
         'imod_reconstruct';...
         'imod_aligned_stack';...
         'novactf';...
         'must_reconstruct';...
         'cryocare_oe_recons';...
         'cryocare_train';...
         'cryocare_predict';...
         'archive';...
         'export_warp';...
         'export_warptools';...
         'export_relion4';...
         'isonet_prepare';...
         'isonet_train';...
         'isonet_predict';...
         'isonet2_prepare';...
         'isonet2_denoise';...
         'isonet2_make_mask';...
         'isonet2_make_particle_mask';...
         'isonet2_refine';...
         'membrain_segment';...
         'arctic';...
         };
     
     
end