function tctf_fields = tm_get_tiltctf_ps_fields()
%% tm_get_tiltctf_ps_fields
% Return the fields for the tiltctf power spectrum calculation structs.
%
% WW 05-2022

%% Fields

tctf_fields = {'stack_name', 'str';...
               'output_name', 'str';...
               'target_def', 'num';...
               'pixelsize', 'num';...
               'xf_name', 'str';...
               'tlt_name', 'str';...
               'lut_name', 'str';...
               'ps_size', 'num';...
               'def_tol', 'num';...
               'fscaling', 'num';...
               'xtilt', 'num';...
               'handedness','num';...
               'write_unstretched', 'boo';...
               'write_negative', 'boo';...
               'visualdebug', 'boo';...
               };
              


        
end
